/*
 * File: app/view/container1.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.container1', {
    extend: 'Ext.Container',

    config: {
        id: 'container1',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'container',
                height: '30%',
                left: 0,
                top: '40%',
                width: '100%',
                layout: {
                    type: 'fit'
                },
                items: [
                    {
                        xtype: 'dataview',
                        scrollable: 'horizontal',
                        inline: {
                            wrap: false
                        },
                        itemTpl: [
                            '<div> aValuebbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb {nombreProvincia}</div>'
                        ],
                        store: 'store1'
                    }
                ]
            },
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'DataView test'
            }
        ]
    }

});